class DiseaseData {
  static Map<String, Map<String, dynamic>> getDiseaseInfo() {
    return {
      'Acne': {
        'nameIndo': 'Jerawat',
        'definition': 'Penyakit peradangan kronis pada unit pilosebaceous (folikel rambut) yang ditandai dengan komedo, papula, pustula, nodul, dan terkadang jaringan parut.',
        'symptoms': [
          'Komedo (blackhead dan whitehead)',
          'Papula dan pustula merah',
          'Nodul keras di bawah kulit',
          'Hiperpigmentasi pasca-inflamasi',
        ],
        'causes': [
          'Peningkatan produksi sebum',
          'Hiperkeratinisasi folikel',
          'Bakteri Cutibacterium acnes',
          'Faktor hormonal',
        ],
        'treatment': [
          'Bersihkan wajah 2x sehari dengan sabun lembut',
          'Gunakan produk non-komedogenik',
          'Hindari memencet jerawat',
          'Konsultasi dokter untuk terapi topikal/oral',
        ],
      },
      'Actinic_Keratosis': {
        'nameIndo': 'Keratosis Aktinik',
        'definition': 'Lesi intraepidermal precancerous (prakanker) yang disebabkan oleh proliferasi atipikal keratinosit akibat paparan sinar ultraviolet (UV) jangka panjang.',
        'symptoms': [
          'Bercak kasar seperti amplas',
          'Bersisik dan kering',
          'Warna kemerahan atau kecokelatan',
          'Muncul di area sering terpapar matahari',
        ],
        'causes': [
          'Paparan sinar UV jangka panjang',
          'Usia lanjut (>50 tahun)',
          'Kulit terang (Fitzpatrick I-II)',
          'Riwayat paparan matahari berlebih',
        ],
        'treatment': [
          'SEGERA konsultasi dokter kulit',
          'Gunakan tabir surya SPF 30+ setiap hari',
          'Hindari paparan matahari langsung',
          'Terapi: cryotherapy, kemoterapi topikal',
        ],
      },
      'Benign_tumors': {
        'nameIndo': 'Tumor Jinak',
        'definition': 'Pertumbuhan neoplasma non-maligna pada kulit yang tidak bermetastasis, mencakup Lipoma, Kista Epidermoid, dan Dermatofibroma.',
        'symptoms': [
          'Benjolan dengan batas tegas',
          'Pertumbuhan lambat',
          'Umumnya tidak nyeri',
          'Tidak menyebar ke organ lain',
        ],
        'causes': [
          'Faktor genetik',
          'Trauma kulit',
          'Penyumbatan kelenjar sebasea',
          'Sebab pasti sering tidak diketahui',
        ],
        'treatment': [
          'Observasi berkala',
          'Eksisi bedah jika mengganggu',
          'Tidak memerlukan terapi khusus',
          'Konsultasi dokter untuk konfirmasi',
        ],
      },
      'Bullous': {
        'nameIndo': 'Penyakit Kulit Melepuh',
        'definition': 'Kelompok penyakit kulit autoimun kronis (seperti Bullous Pemphigoid) yang ditandai dengan pembentukan bula (lepuhan besar) subepidermal.',
        'symptoms': [
          'Lepuhan besar berisi cairan',
          'Kulit eritematosa (merah)',
          'Gatal hebat',
          'Lepuhan tegang tidak mudah pecah',
        ],
        'causes': [
          'Reaksi autoantibodi IgG',
          'Gangguan hemidesmosom kulit',
          'Pemicu: obat-obatan, infeksi',
          'Faktor genetik dan imunologis',
        ],
        'treatment': [
          'SEGERA ke dokter/rumah sakit',
          'Jangan pecahkan lepuhan',
          'Terapi: kortikosteroid sistemik',
          'Perawatan luka steril',
        ],
      },
      'Candidiasis': {
        'nameIndo': 'Kandidiasis Kutis',
        'definition': 'Infeksi oportunistik pada kulit dan mukosa yang disebabkan oleh jamur genus Candida (terutama C. albicans).',
        'symptoms': [
          'Plak merah cerah basah',
          'Lesi satelit di sekitar area utama',
          'Gatal dan rasa panas',
          'Muncul di area lipatan kulit',
        ],
        'causes': [
          'Jamur Candida albicans',
          'Kelembapan tinggi',
          'Kebersihan kurang',
          'Sistem imun lemah, diabetes',
        ],
        'treatment': [
          'Jaga area tetap kering',
          'Gunakan antijamur topikal (miconazole)',
          'Ganti pakaian yang menyerap keringat',
          'Konsultasi dokter jika tidak membaik',
        ],
      },
      'DrugEruption': {
        'nameIndo': 'Erupsi Obat',
        'definition': 'Reaksi hipersensitivitas kulit terhadap pemberian obat sistemik, paling sering bermanifestasi sebagai erupsi eksantematosa (morbiliformis).',
        'symptoms': [
          'Ruam merah simetris',
          'Menyebar dari batang tubuh',
          'Gatal',
          'Muncul 7-14 hari setelah konsumsi obat',
        ],
        'causes': [
          'Antibiotik (penisilin, sulfonamid)',
          'NSAID (anti-inflamasi)',
          'Antiepilepsi',
          'Reaksi hipersensitivitas tipe IV',
        ],
        'treatment': [
          'HENTIKAN obat pemicu (konsultasi dokter)',
          'Jangan hentikan obat tanpa saran dokter',
          'Antihistamin untuk gatal',
          'Monitor gejala berat (demam, sesak)',
        ],
      },
      'Eczema': {
        'nameIndo': 'Eksim / Dermatitis',
        'definition': 'Inflamasi kulit non-infeksius yang ditandai dengan gangguan barier epidermis (kulit kering, pecah-pecah).',
        'symptoms': [
          'Kulit kering dan gatal',
          'Kemerahan dan bengkak',
          'Vesikel (gelembung kecil)',
          'Likenifikasi (penebalan kulit)',
        ],
        'causes': [
          'Faktor genetik (atopik)',
          'Alergen (sabun, deterjen)',
          'Iritasi eksternal',
          'Stres dan cuaca kering',
        ],
        'treatment': [
          'Pelembap intensif 2-3x sehari',
          'Hindari pemicu (sabun keras, wol)',
          'Kortikosteroid topikal (resep dokter)',
          'Kompres dingin untuk meredakan gatal',
        ],
      },
      'Infestations_Bites': {
        'nameIndo': 'Infestasi & Gigitan',
        'definition': 'Infeksi ektoparasit (scabies) atau reaksi gigitan artropoda (nyamuk, kutu) yang menyebabkan lesi kulit gatal.',
        'symptoms': [
          'Gatal hebat terutama malam hari',
          'Papula atau vesikel',
          'Terowongan kulit (pada scabies)',
          'Pola gigitan berderet',
        ],
        'causes': [
          'Sarcoptes scabiei (tungau)',
          'Gigitan serangga (nyamuk, kutu)',
          'Kontak langsung dengan penderita',
          'Kebersihan buruk',
        ],
        'treatment': [
          'Scabies: permethrin 5% topikal',
          'Cuci pakaian dan sprei air panas',
          'Obat antihistamin untuk gatal',
          'Rawat seluruh anggota keluarga',
        ],
      },
      'Lichen': {
        'nameIndo': 'Liken',
        'definition': 'Lichen Planus adalah penyakit inflamasi autoimun; Lichen Simplex adalah penebalan kulit akibat garukan kronis.',
        'symptoms': [
          'Papula datar berwarna ungu',
          'Sangat gatal',
          'Penebalan kulit (likenifikasi)',
          'Sering di pergelangan tangan',
        ],
        'causes': [
          'Reaksi autoimun (Lichen Planus)',
          'Siklus gatal-garuk kronis',
          'Stres psikologis',
          'Pemicu: obat, infeksi hepatitis C',
        ],
        'treatment': [
          'Kortikosteroid topikal poten',
          'Hentikan siklus garuk',
          'Antihistamin untuk gatal',
          'Konsultasi dokter kulit',
        ],
      },
      'Lupus': {
        'nameIndo': 'Lupus Eritematosus Kutaneus',
        'definition': 'Manifestasi kulit dari penyakit autoimun lupus, bisa akut (malar rash) atau kronis (discoid lupus).',
        'symptoms': [
          'Ruam kupu-kupu di wajah',
          'Sensitif terhadap sinar matahari',
          'Plak bersisik (discoid)',
          'Kerontokan rambut permanen',
        ],
        'causes': [
          'Gangguan autoimun sistemik',
          'Faktor genetik',
          'Pemicu: sinar UV, stres, infeksi',
          'Hormon (lebih sering pada wanita)',
        ],
        'treatment': [
          'Tabir surya SPF 50+ wajib',
          'Hindari paparan matahari langsung',
          'Kortikosteroid topikal/sistemik',
          'Konsultasi reumatologi',
        ],
      },
      'Moles': {
        'nameIndo': 'Tahi Lalat (Nevus)',
        'definition': 'Tumor jinak melanosit (sel pigmen) yang berproliferasi membentuk nest di epidermis atau dermis.',
        'symptoms': [
          'Bercak cokelat/hitam',
          'Berbatas tegas',
          'Permukaan rata atau berjonjot',
          'Ukuran umumnya <6mm',
        ],
        'causes': [
          'Faktor genetik',
          'Paparan sinar matahari',
          'Proliferasi melanosit jinak',
          'Hormon (pubertas, kehamilan)',
        ],
        'treatment': [
          'Observasi rutin (ABCDE)',
          'Konsultasi jika ada perubahan',
          'Eksisi jika dicurigai ganas',
          'Lindungi dari sinar UV',
        ],
      },
      'Psoriasis': {
        'nameIndo': 'Psoriasis',
        'definition': 'Penyakit inflamasi sistemik kronis yang dimediasi sel T, menyebabkan hiperproliferasi keratinosit.',
        'symptoms': [
          'Plak merah tebal berbatas tegas',
          'Sisik berlapis warna perak',
          'Gatal dan nyeri',
          'Auspitz sign (pendarahan saat sisik dilepas)',
        ],
        'causes': [
          'Faktor genetik dan autoimun',
          'Pemicu: trauma, stres, infeksi',
          'Hiperproliferasi keratinosit',
          'Gangguan sistem imun',
        ],
        'treatment': [
          'Kortikosteroid topikal',
          'Pelembap intensif',
          'Fototerapi (sinar UV terkontrol)',
          'Obat sistemik (methotrexate, biologics)',
        ],
      },
      'Rosacea': {
        'nameIndo': 'Rosacea',
        'definition': 'Dermatosis inflamasi kronis pada wajah yang melibatkan kelainan vaskular.',
        'symptoms': [
          'Kemerahan persisten di wajah',
          'Flushing (muka tiba-tiba merah)',
          'Pembuluh darah terlihat',
          'Papula dan pustula tanpa komedo',
        ],
        'causes': [
          'Kelainan vaskular',
          'Pemicu: makanan pedas, alkohol',
          'Paparan panas dan stres',
          'Faktor genetik',
        ],
        'treatment': [
          'Hindari pemicu (pedas, alkohol)',
          'Tabir surya non-komedogenik',
          'Metronidazole topikal',
          'Konsultasi dokter kulit',
        ],
      },
      'Seborrh_Keratoses': {
        'nameIndo': 'Keratosis Seboroik',
        'definition': 'Tumor jinak epidermis yang sering terjadi pada usia lanjut, berasal dari proliferasi keratinosit.',
        'symptoms': [
          'Lesi cokelat hingga hitam',
          'Permukaan berminyak dan kasar',
          'Kesan "menempel" pada kulit',
          'Tidak nyeri atau gatal',
        ],
        'causes': [
          'Faktor usia (>40 tahun)',
          'Genetik',
          'Proliferasi keratinosit jinak',
          'Paparan sinar matahari',
        ],
        'treatment': [
          'Tidak memerlukan terapi',
          'Cryotherapy untuk kosmetik',
          'Elektrokauter atau kuretase',
          'Tidak berpotensi ganas',
        ],
      },
      'SkinCancer': {
        'nameIndo': 'Kanker Kulit',
        'definition': 'Keganasan kulit meliputi Karsinoma Sel Basal (BCC), Karsinoma Sel Skuamosa (SCC), dan Melanoma Maligna.',
        'symptoms': [
          'Lesi tidak sembuh >3 minggu',
          'Perubahan warna, ukuran, bentuk',
          'Pendarahan spontan',
          'Asimetri dan batas tidak teratur',
        ],
        'causes': [
          'Paparan sinar UV kronis',
          'Riwayat keluarga melanoma',
          'Kulit terang',
          'Riwayat luka bakar matahari',
        ],
        'treatment': [
          'SEGERA konsultasi dokter onkologi',
          'Biopsi untuk konfirmasi',
          'Eksisi bedah',
          'Kemoterapi/radioterapi jika stadium lanjut',
        ],
      },
      'Sun_Sunlight_Damage': {
        'nameIndo': 'Kerusakan Sinar Matahari (Photoaging)',
        'definition': 'Kerusakan kulit kumulatif akibat paparan sinar UV kronis yang menyebabkan degradasi kolagen dan elastin.',
        'symptoms': [
          'Kulit berkerut dalam',
          'Tekstur kasar (leathery)',
          'Bintik-bintik hitam (age spots)',
          'Kulit kusam dan atrofi',
        ],
        'causes': [
          'Paparan sinar UV kronis',
          'Degradasi kolagen',
          'Akumulasi elastin abnormal',
          'Radikal bebas',
        ],
        'treatment': [
          'Tabir surya SPF 30+ setiap hari',
          'Hindari paparan sinar 10:00-14:00',
          'Retinoid topikal (resep dokter)',
          'Perawatan laser/chemical peeling',
        ],
      },
      'Tinea': {
        'nameIndo': 'Kurap (Dermatofitosis)',
        'definition': 'Infeksi jamur superfisial oleh dermatofita yang memiliki afinitas terhadap keratin.',
        'symptoms': [
          'Lesi berbentuk cincin',
          'Tepi aktif merah dan bersisik',
          'Tengah lesi cenderung sembuh',
          'Gatal',
        ],
        'causes': [
          'Jamur dermatofita (Trichophyton)',
          'Kontak dengan penderita/hewan',
          'Kelembapan tinggi',
          'Kebersihan kurang',
        ],
        'treatment': [
          'Antijamur topikal (clotrimazole)',
          'Jaga area tetap kering',
          'Hindari berbagi handuk/pakaian',
          'Antijamur oral jika luas',
        ],
      },
      'Unknown_Normal': {
        'nameIndo': 'Kulit Normal',
        'definition': 'Tampilan kulit sehat dengan epidermis, dermis, dan adneksa kulit yang utuh tanpa patologi.',
        'symptoms': [
          'Kulit mulus tanpa lesi',
          'Warna merata',
          'Tidak ada kemerahan atau sisik',
          'Tekstur normal',
        ],
        'causes': [
          'Tidak ada kelainan',
          'Variasi pigmentasi normal',
          'Kulit sehat',
        ],
        'treatment': [
          'Jaga kebersihan kulit',
          'Pelembap rutin',
          'Tabir surya saat aktivitas luar',
          'Pola hidup sehat',
        ],
      },
      'Vascular_Tumors': {
        'nameIndo': 'Tumor Vaskular',
        'definition': 'Anomali vaskular berupa proliferasi sel endotel, seperti Hemangioma Infantil atau Granuloma Piogenik.',
        'symptoms': [
          'Benjolan merah terang',
          'Mudah berdarah (granuloma)',
          'Tumbuh cepat',
          'Hemangioma: involusi spontan',
        ],
        'causes': [
          'Proliferasi pembuluh darah',
          'Trauma minor (granuloma)',
          'Faktor genetik',
          'Hormon (hemangioma)',
        ],
        'treatment': [
          'Observasi (hemangioma infantil)',
          'Eksisi atau kauterisasi',
          'Beta-blocker (hemangioma besar)',
          'Konsultasi dokter anak/kulit',
        ],
      },
      'Vasculitis': {
        'nameIndo': 'Vaskulitis Kutaneus',
        'definition': 'Inflamasi dinding pembuluh darah dermal yang menyebabkan kerusakan vaskular.',
        'symptoms': [
          'Bintik merah-ungu teraba (purpura)',
          'Tidak hilang dengan penekanan',
          'Sering di tungkai bawah',
          'Nyeri atau gatal',
        ],
        'causes': [
          'Reaksi autoimun',
          'Infeksi (Streptococcus)',
          'Obat-obatan',
          'Penyakit jaringan ikat',
        ],
        'treatment': [
          'Konsultasi dokter/reumatologi',
          'Kortikosteroid sistemik',
          'Hentikan obat pemicu',
          'Terapi penyakit dasar',
        ],
      },
      'Vitiligo': {
        'nameIndo': 'Vitiligo',
        'definition': 'Gangguan depigmentasi didapat akibat destruksi melanosit epidermis secara autoimun.',
        'symptoms': [
          'Bercak putih susu',
          'Berbatas tegas',
          'Tidak gatal atau nyeri',
          'Sering simetris',
        ],
        'causes': [
          'Autoimun (destruksi melanosit)',
          'Faktor genetik',
          'Stres oksidatif',
          'Trauma (Koebner phenomenon)',
        ],
        'treatment': [
          'Kortikosteroid topikal',
          'Fototerapi (UVB narrowband)',
          'Tabir surya tinggi (area depigmentasi)',
          'Konseling psikologis',
        ],
      },
      'Warts': {
        'nameIndo': 'Kutil (Veruka)',
        'definition': 'Infeksi intraepidermal jinak yang disebabkan oleh Human Papillomavirus (HPV).',
        'symptoms': [
          'Benjolan kasar (verukosa)',
          'Bintik hitam kecil di tengah',
          'Tidak nyeri (kecuali plantar)',
          'Tumbuh lambat',
        ],
        'causes': [
          'Human Papillomavirus (HPV)',
          'Kontak langsung kulit',
          'Autoinokulasi',
          'Sistem imun lemah',
        ],
        'treatment': [
          'Cryotherapy (nitrogen cair)',
          'Salicylic acid topikal',
          'Jangan garuk atau dikorek',
          'Hindari kontak langsung',
        ],
      },
    };
  }
}